;~ $Gfn=IniRead("config.ini","Gui","formn","Auto")
;~ $Gf1=IniRead("config.ini","Gui","form1",230)
;~ $Gf2=IniRead("config.ini","Gui","form2",185)
;~ $Gf3=IniRead("config.ini","Gui","form3",230)
;~ $Gf4=IniRead("config.ini","Gui","form4",140)
;~ $Gogn=IniRead("config.ini","Gui","input1n","Ogloszenia")
;~ $Gog1=IniRead("config.ini","Gui","input11",10)
;~ $Gog2=IniRead("config.ini","Gui","input12",10)
;~ $Gog3=IniRead("config.ini","Gui","input13",100)
;~ $Gog4=IniRead("config.ini","Gui","input14",21)
;~ $Gdbn=IniRead("config.ini","Gui","open dialogn","Przegl¹daj")
;~ $Gdb1=IniRead("config.ini","Gui","open dialog1",120)
;~ $Gdb2=IniRead("config.ini","Gui","open dialog2",10)
;~ $Gdb3=IniRead("config.ini","Gui","open dialog3",75)
;~ $Gdb4=IniRead("config.ini","Gui","open dialog4",20)
;~ $Gppn=IniRead("config.ini","Gui","input2n","Pe³na nazwa")
;~ $Gpp1=IniRead("config.ini","Gui","input21",10)
;~ $Gpp2=IniRead("config.ini","Gui","input22",40)
;~ $Gpp3=IniRead("config.ini","Gui","input23",100)
;~ $Gpp4=IniRead("config.ini","Gui","input24",21)
;~ $Gpsn=IniRead("config.ini","Gui","input3n","Skrócona nazwa")
;~ $Gps1=IniRead("config.ini","Gui","input31",10)
;~ $Gps2=IniRead("config.ini","Gui","input32",70)
;~ $Gps3=IniRead("config.ini","Gui","input33",100)
;~ $Gps4=IniRead("config.ini","Gui","input34",21)
;~ $Gy1=IniRead("config.ini","Gui","input41",10)
;~ $Gy2=IniRead("config.ini","Gui","input42",100)
;~ $Gy3=IniRead("config.ini","Gui","input43",30)
;~ $Gy4=IniRead("config.ini","Gui","input44",21)
;~ $Gm1=IniRead("config.ini","Gui","input51",45)
;~ $Gm2=IniRead("config.ini","Gui","input52",100)
;~ $Gm3=IniRead("config.ini","Gui","input53",20)
;~ $Gm4=IniRead("config.ini","Gui","input54",21)
;~ $Gd1=IniRead("config.ini","Gui","input61",70)
;~ $Gd2=IniRead("config.ini","Gui","input62",100)
;~ $Gd3=IniRead("config.ini","Gui","input63",20)
;~ $Gd4=IniRead("config.ini","Gui","input64",21)
;~ $Ggn=IniRead("config.ini","Gui","grupan","Funkcje")
;~ $Gg1=IniRead("config.ini","Gui","grupa1",112)
;~ $Gg2=IniRead("config.ini","Gui","grupa2",30)
;~ $Gg3=IniRead("config.ini","Gui","grupa3",113)
;~ $Gg4=IniRead("config.ini","Gui","grupa4",117)
;~ $Gin=IniRead("config.ini","Gui","chbox1n","Index")
;~ $Gi1=IniRead("config.ini","Gui","chbox11",120)
;~ $Gi2=IniRead("config.ini","Gui","chbox12",45)
;~ $Gi3=IniRead("config.ini","Gui","chbox13",90)
;~ $Gi4=IniRead("config.ini","Gui","chbox14",20)
;~ $Gon=IniRead("config.ini","Gui","chbox2n","Og³oszenia")
;~ $Go1=IniRead("config.ini","Gui","chbox21",120)
;~ $Go2=IniRead("config.ini","Gui","chbox22",65)
;~ $Go3=IniRead("config.ini","Gui","chbox23",90)
;~ $Go4=IniRead("config.ini","Gui","chbox24",20)
;~ $Gpon=IniRead("config.ini","Gui","chbox3n","Plik og³oszenia")
;~ $Gpo1=IniRead("config.ini","Gui","chbox31",120)
;~ $Gpo2=IniRead("config.ini","Gui","chbox32",85)
;~ $Gpo3=IniRead("config.ini","Gui","chbox33",90)
;~ $Gpo4=IniRead("config.ini","Gui","chbox34",20)
;~ $Gftpn=IniRead("config.ini","Gui","chbox4n","Wyœlij na ftp")
;~ $Gftp1=IniRead("config.ini","Gui","chbox41",120)
;~ $Gftp2=IniRead("config.ini","Gui","chbox42",105)
;~ $Gftp3=IniRead("config.ini","Gui","chbox43",90)
;~ $Gftp4=IniRead("config.ini","Gui","chbox44",20)
;~ $Gsprn=IniRead("config.ini","Gui","chbox5n","Kontrola")
;~ $Gspr1=IniRead("config.ini","Gui","chbox51",120)
;~ $Gspr2=IniRead("config.ini","Gui","chbox52",125)
;~ $Gspr3=IniRead("config.ini","Gui","chbox53",90)
;~ $Gspr4=IniRead("config.ini","Gui","chbox54",20)
;~ $Gup2n=IniRead("config.ini","Gui","butonok2n","Zapisz")
;~ $Gup21=IniRead("config.ini","Gui","butonok21",70)
;~ $Gup22=IniRead("config.ini","Gui","butonok22",155)
;~ $Gup23=IniRead("config.ini","Gui","butonok23",75)
;~ $Gup24=IniRead("config.ini","Gui","butonok24",25)
;~ $Gup1n=IniRead("config.ini","Gui","butonok1","Wyœlij")

;~ $dian=IniRead("config.ini","napisy","drogloszenia","Wybierz plik z og³oszeniami")
;~ $dias=IniRead("config.ini","napisy","dirogloszenia","C:\Documents and Settings\Admin\Moje dokumenty\Dropbox\WWW\pliki\og³oszenia")
;~ $mt=IniRead("config.ini","napisy","msgboxtytu³","Test")
;~ $mp=IniRead("config.ini","napisy","msgboxpytanie","Strona dobrze wygl¹da?")
;~ $mt=IniRead("config.ini","napisy","b³¹dftptytu³","B³¹d!")
;~ $mp=IniRead("config.ini","napisy","msgboxpytanie","Wyst¹pi³ b³¹d podczas ³¹czenia z serwerem ftp sprawdŸ dane")
;~ $mt=IniRead("config.ini","napisy","b³¹dftptytu³","Test")
;~ $mp=IniRead("config.ini","napisy","msgboxpytanie","Spróbuj jeszcze raz")

;~ $pog1=IniRead("config.ini","funkcje","pog1",'<h1 class="atitle" style="background-image: none; padding-left: 0px; margin-left: 10px;"><br><a href="pliki/')
;~ $pog2=IniRead("config.ini","funkcje","pog2",'.html">Og³oszenia - ')
;~ $pog3=IniRead("config.ini","funkcje","pog3",'</a></h1><h1 class="atitle" style="background-image: none; padding-left: 0px; margin-left: 10px; text-align: right;"><small><a style="color: rgb(79, 130, 203); font-weight: normal;" href="pliki/')
;~ $pog4=IniRead("config.ini","funkcje","pog4",'.html">czytaj og³oszenia</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ')
;~ $pog5=IniRead("config.ini","funkcje","pog5",'&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;</small></h1>')
;~ $co1=IniRead("config.ini","funkcje","co1",'<h1 class="atitle" style="background-image: none; padding-left: 0px; margin-left: 10px;"><br>')
;~ $cod1=IniRead("config.ini","funkcje","cod1","-2")
;~ $cod2=IniRead("config.ini","funkcje","cod2","+5")
;~ $ci=IniRead("config.ini","funkcje","ci",'<div class="post">')
;~ $cid1=IniRead("config.ini","funkcje","cid1","+18")
;~ $cid2=IniRead("config.ini","funkcje","cid2","-1")
;~ $tih=IniRead("config.ini","funkcje","tih",'<div class="post">')
;~ $po11=IniRead("config.ini","funkcje","po11",'<h1 class="atitle" style="background-image: none; padding-left: 0px; margin-left: 10px;">Strona g³&oacute;wna</h1><p style="margin: 0pt; padding: 0pt; text-align: right; color: rgb(102, 102, 102); font-weight: bold;"><span class="date">')
;~ $po12=IniRead("config.ini","funkcje","po12",'</span></p><p style="text-align: center; font-weight: bold;"><a href="../images/klepsydra.jpg"><img style="border: 0px solid ;" alt="" src="../images/klepsydra.jpeg"><br></a>')
;~ $po13=IniRead("config.ini","funkcje","po13","</p><p>")
;~ $po14=IniRead("config.ini","funkcje","po14","</p>")
;~ $po21=IniRead("config.ini","funkcje","po21",'<h1 class="atitle" style="background-image: none; padding-left: 0px; margin-left: 10px;">Og³oszenia</h1><p style="margin: 0pt; padding: 0pt; text-align: right; color: rgb(102, 102, 102); font-weight: bold;"><span class="date">')
;~ $po22=IniRead("config.ini","funkcje","po22",'</span></p><p style="text-align: center; font-weight: bold;"></a>')
;~ $po23=IniRead("config.ini","funkcje","po23","</p><p>")
;~ $po24=IniRead("config.ini","funkcje","po24","</p>")

;~ $host =IniRead("config.ini","ftp","host", "ftp.strefa.pl")
;~ $dir =IniRead("config.ini","ftp","dir","/")
;~ $user =IniRead("config.ini","ftp","user","rdzawka+marianie.pl")
;~ $pwd = IniRead("config.ini","ftp","pass","MICobid83#")
;~ $port =IniRead("config.ini","ftp","port",21)
;~ $link =IniRead("config.ini","ftp","link","http://rdzawka.marianie.pl/")

;~ $geti=IniRead("config.ini","pliki","index","index.html")
;~ $geto=IniRead("config.ini","pliki","ogloszenia","og.html")
;~ $getpo=IniRead("config.ini","pliki","pogloszenia","cpog.html")
;~ $pom=IniRead("config.ini","pliki","pogloszeniamnaftp","/pliki/")
;~ $flog=IniRead("config.ini","pliki","log","log.txt")
;~ $fkodowanie=IniRead("config.ini","pliki","kodowanie","kodowanie.ini")
;~ $li=IniRead("config.ini","pliki","linkindex","http://rdzawka.marianie.pl/index.html")
;~ $lo=IniRead("config.ini","pliki","linkogloszenia","http://rdzawka.marianie.pl/ogloszenia.html")
;~ $lpo=IniRead("config.ini","pliki","kodowanie","cpog.html")
;~ $ti=IniRead("config.ini","pliki","temp1","i.html")
;~ $to=IniRead("config.ini","pliki","temp2","o.html")
;~ $tpo=IniRead("config.ini","pliki","temp3","po.html")
$Gfn=iniwrite("config.ini","Gui","formn","Auto")
$Gf1=iniwrite("config.ini","Gui","form1",230)
$Gf2=iniwrite("config.ini","Gui","form2",185)
$Gf3=iniwrite("config.ini","Gui","form3",230)
$Gf4=iniwrite("config.ini","Gui","form4",140)
$Gogn=iniwrite("config.ini","Gui","input1n","Ogloszenia")
$Gog1=iniwrite("config.ini","Gui","input11",10)
$Gog2=iniwrite("config.ini","Gui","input12",10)
$Gog3=iniwrite("config.ini","Gui","input13",100)
$Gog4=iniwrite("config.ini","Gui","input14",21)
$Gdbn=iniwrite("config.ini","Gui","open dialogn","Przegl¹daj")
$Gdb1=iniwrite("config.ini","Gui","open dialog1",120)
$Gdb2=iniwrite("config.ini","Gui","open dialog2",10)
$Gdb3=iniwrite("config.ini","Gui","open dialog3",75)
$Gdb4=iniwrite("config.ini","Gui","open dialog4",20)
$Gppn=iniwrite("config.ini","Gui","input2n","Pe³na nazwa")
$Gpp1=iniwrite("config.ini","Gui","input21",10)
$Gpp2=iniwrite("config.ini","Gui","input22",40)
$Gpp3=iniwrite("config.ini","Gui","input23",100)
$Gpp4=iniwrite("config.ini","Gui","input24",21)
$Gpsn=iniwrite("config.ini","Gui","input3n","Skrócona nazwa")
$Gps1=iniwrite("config.ini","Gui","input31",10)
$Gps2=iniwrite("config.ini","Gui","input32",70)
$Gps3=iniwrite("config.ini","Gui","input33",100)
$Gps4=iniwrite("config.ini","Gui","input34",21)
$Gy1=iniwrite("config.ini","Gui","input41",10)
$Gy2=iniwrite("config.ini","Gui","input42",100)
$Gy3=iniwrite("config.ini","Gui","input43",30)
$Gy4=iniwrite("config.ini","Gui","input44",21)
$Gm1=iniwrite("config.ini","Gui","input51",45)
$Gm2=iniwrite("config.ini","Gui","input52",100)
$Gm3=iniwrite("config.ini","Gui","input53",20)
$Gm4=iniwrite("config.ini","Gui","input54",21)
$Gd1=iniwrite("config.ini","Gui","input61",70)
$Gd2=iniwrite("config.ini","Gui","input62",100)
$Gd3=iniwrite("config.ini","Gui","input63",20)
$Gd4=iniwrite("config.ini","Gui","input64",21)
$Ggn=iniwrite("config.ini","Gui","grupan","Funkcje")
$Gg1=iniwrite("config.ini","Gui","grupa1",112)
$Gg2=iniwrite("config.ini","Gui","grupa2",30)
$Gg3=iniwrite("config.ini","Gui","grupa3",113)
$Gg4=iniwrite("config.ini","Gui","grupa4",117)
$Gin=iniwrite("config.ini","Gui","chbox1n","Index")
$Gi1=iniwrite("config.ini","Gui","chbox11",120)
$Gi2=iniwrite("config.ini","Gui","chbox12",45)
$Gi3=iniwrite("config.ini","Gui","chbox13",90)
$Gi4=iniwrite("config.ini","Gui","chbox14",20)
$Gon=iniwrite("config.ini","Gui","chbox2n","Og³oszenia")
$Go1=iniwrite("config.ini","Gui","chbox21",120)
$Go2=iniwrite("config.ini","Gui","chbox22",65)
$Go3=iniwrite("config.ini","Gui","chbox23",90)
$Go4=iniwrite("config.ini","Gui","chbox24",20)
$Gpon=iniwrite("config.ini","Gui","chbox3n","Plik og³oszenia")
$Gpo1=iniwrite("config.ini","Gui","chbox31",120)
$Gpo2=iniwrite("config.ini","Gui","chbox32",85)
$Gpo3=iniwrite("config.ini","Gui","chbox33",90)
$Gpo4=iniwrite("config.ini","Gui","chbox34",20)
$Gftpn=iniwrite("config.ini","Gui","chbox4n","Wyœlij na ftp")
$Gftp1=iniwrite("config.ini","Gui","chbox41",120)
$Gftp2=iniwrite("config.ini","Gui","chbox42",105)
$Gftp3=iniwrite("config.ini","Gui","chbox43",90)
$Gftp4=iniwrite("config.ini","Gui","chbox44",20)
$Gsprn=iniwrite("config.ini","Gui","chbox5n","Kontrola")
$Gspr1=iniwrite("config.ini","Gui","chbox51",120)
$Gspr2=iniwrite("config.ini","Gui","chbox52",125)
$Gspr3=iniwrite("config.ini","Gui","chbox53",90)
$Gspr4=iniwrite("config.ini","Gui","chbox54",20)
$Gup2n=iniwrite("config.ini","Gui","butonok2n","Zapisz")
$Gup21=iniwrite("config.ini","Gui","butonok21",70)
$Gup22=iniwrite("config.ini","Gui","butonok22",155)
$Gup23=iniwrite("config.ini","Gui","butonok23",75)
$Gup24=iniwrite("config.ini","Gui","butonok24",25)
$Gup1n=iniwrite("config.ini","Gui","butonok1","Wyœlij")

$dian=iniwrite("config.ini","napisy","drogloszenia","Wybierz plik z og³oszeniami")
$dias=iniwrite("config.ini","napisy","dirogloszenia","C:\Documents and Settings\Admin\Moje dokumenty\Dropbox\WWW\pliki\og³oszenia")
$mt=iniwrite("config.ini","napisy","msgboxtytu³","Test")
$mp=iniwrite("config.ini","napisy","msgboxpytanie","Strona dobrze wygl¹da?")
$mt=iniwrite("config.ini","napisy","b³¹dftptytu³","B³¹d!")
$mp=iniwrite("config.ini","napisy","msgboxpytanie","Wyst¹pi³ b³¹d podczas ³¹czenia z serwerem ftp sprawdŸ dane")
$mt=iniwrite("config.ini","napisy","b³¹dftptytu³","Test")
$mp=iniwrite("config.ini","napisy","msgboxpytanie","Spróbuj jeszcze raz")

$pog1=iniwrite("config.ini","funkcje","pog1",'<h1 class="atitle" style="background-image: none; padding-left: 0px; margin-left: 10px;"><br><a href="pliki/')
$pog2=iniwrite("config.ini","funkcje","pog2",'.html">Og³oszenia - ')
$pog3=iniwrite("config.ini","funkcje","pog3",'</a></h1><h1 class="atitle" style="background-image: none; padding-left: 0px; margin-left: 10px; text-align: right;"><small><a style="color: rgb(79, 130, 203); font-weight: normal;" href="pliki/')
$pog4=iniwrite("config.ini","funkcje","pog4",'.html">czytaj og³oszenia</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ')
$pog5=iniwrite("config.ini","funkcje","pog5",'&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;</small></h1>')
$co1=iniwrite("config.ini","funkcje","co1",'<h1 class="atitle" style="background-image: none; padding-left: 0px; margin-left: 10px;"><br>')
$cod1=iniwrite("config.ini","funkcje","cod1","-2")
$cod2=iniwrite("config.ini","funkcje","cod2","+5")
$ci=iniwrite("config.ini","funkcje","ci",'<div class="post">')
$cid1=iniwrite("config.ini","funkcje","cid1","+18")
$cid2=iniwrite("config.ini","funkcje","cid2","-1")
$tih=iniwrite("config.ini","funkcje","tih",'<div class="post">')
$po11=iniwrite("config.ini","funkcje","po11",'<h1 class="atitle" style="background-image: none; padding-left: 0px; margin-left: 10px;">Strona g³&oacute;wna</h1><p style="margin: 0pt; padding: 0pt; text-align: right; color: rgb(102, 102, 102); font-weight: bold;"><span class="date">')
$po12=iniwrite("config.ini","funkcje","po12",'</span></p><p style="text-align: center; font-weight: bold;"><a href="../images/klepsydra.jpg"><img style="border: 0px solid ;" alt="" src="../images/klepsydra.jpeg"><br></a>')
$po13=iniwrite("config.ini","funkcje","po13","</p><p>")
$po14=iniwrite("config.ini","funkcje","po14","</p>")
$po21=iniwrite("config.ini","funkcje","po21",'<h1 class="atitle" style="background-image: none; padding-left: 0px; margin-left: 10px;">Og³oszenia</h1><p style="margin: 0pt; padding: 0pt; text-align: right; color: rgb(102, 102, 102); font-weight: bold;"><span class="date">')
$po22=iniwrite("config.ini","funkcje","po22",'</span></p><p style="text-align: center; font-weight: bold;"></a>')
$po23=iniwrite("config.ini","funkcje","po23","</p><p>")
$po24=iniwrite("config.ini","funkcje","po24","</p>")

$host =iniwrite("config.ini","ftp","host", "ftp.strefa.pl")
$dir =iniwrite("config.ini","ftp","dir","/")
$user =iniwrite("config.ini","ftp","user","rdzawka+marianie.pl")
$pwd = iniwrite("config.ini","ftp","pass","MICobid83#")
$port =iniwrite("config.ini","ftp","port",21)
$link =iniwrite("config.ini","ftp","link","http://rdzawka.marianie.pl/")

$geti=iniwrite("config.ini","pliki","index","index.html")
$geto=iniwrite("config.ini","pliki","ogloszenia","og.html")
$getpo=iniwrite("config.ini","pliki","pogloszenia","cpog.html")
$pom=iniwrite("config.ini","pliki","pogloszeniamnaftp","/pliki/")
$flog=iniwrite("config.ini","pliki","log","log.txt")
$fkodowanie=iniwrite("config.ini","pliki","kodowanie","kodowanie.ini")
$li=iniwrite("config.ini","pliki","linkindex","http://rdzawka.marianie.pl/index.html")
$lo=iniwrite("config.ini","pliki","linkogloszenia","http://rdzawka.marianie.pl/ogloszenia.html")
$lpo=iniwrite("config.ini","pliki","kodowanie","cpog.html")
$ti=iniwrite("config.ini","pliki","temp1","i.html")
$to=iniwrite("config.ini","pliki","temp2","o.html")
$tpo=iniwrite("config.ini","pliki","temp3","po.html")