Opt("MouseCoordMode", 0) ;wspó³rzêdne wzglêdne
Opt("SendKeyDelay", 100)  ;czas miêdzy "wciœniêciami" klawiszy

Run(@WindowsDir & "\Notepad.exe") ;uruchomienie notatnika
Sleep(1000)
If ProcessExists("notepad.exe") Then
   MsgBox(0, "Test:", "Notatnik zosta³ uruchomiony, aby kontynuowaæ naciœnij OK")
Else
   MsgBox(0, "Test:", "Notatnik nie zosta³ uruchomiony, aby kontynuowaæ naciœnij OK")
EndIf
Sleep(1000)

Send("Jan Worwa"&@LF&"z domu Worwa") ;pisanie do edytora
Sleep(100)
Send("{ENTER}") ;klawisz ENTER
Sleep(2000)
$size=WinGetClientSize("[ACTIVE]") ;odczytanie wielkoœci okna
MouseMove($size[0]-10,10,50) ;przesuniêcie kursora myszki
Sleep(500)
MouseClick("left") ;klik lewym klawiszem
Sleep(500)
Send("{ENTER}")
Sleep(500)
Send("Ciota.txt")
Sleep(250)
Send("{TAB}")
Send("{TAB}")
Send("{TAB}")
Send("{TAB}")
Send("{TAB}")
Send("{TAB}")    ;wejœcie na œciezke
MouseMove(680,300)
MouseClick("left")
Send("{ENTER}")
Send("Pulpit")
Send("{ENTER}")
Sleep(500)
$size=WinGetClientSize("[ACTIVE]")
MouseMove($size[0]-50,450,50)
MouseClick("left")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("{Backspace}")
Send("¯arcikowa³em")
Sleep(1000)
Send("{Enter}")
Send("{Enter}")
Send("Jasiu ")
$size=WinGetClientSize("[ACTIVE]") ;odczytanie wielkoœci okna
MouseMove($size[0]-10,10,50) ;przesuniêcie kursora myszki
Sleep(500)
MouseClick("left") ;klik lewym klawiszem
Sleep(500)
Send("{ENTER}")
Sleep(500)
Send("Jaœ.txt")
Sleep(100)
Send("{TAB}")
Send("{TAB}")
Send("{TAB}")
Send("{TAB}")
Send("{TAB}")
Send("{TAB}")    ;wejœcie na œciezke
MouseMove(680,300)
MouseClick("left")
Send("{ENTER}")
Send("Pulpit")
Send("{ENTER}")
Sleep(500)
$size=WinGetClientSize("[ACTIVE]")
MouseMove($size[0]-150,450,50)
MouseClick("left")